### ISSUE TITLE
Interested in updating?

### ISSUE THREAD

**Issue by jsrhodes15** [faboulaws/fakingoose#25]
Hi, I found this lib when searching on npm, and it is _almost_ perfect for what I need. The main problem is that mongoose type DECIMAL128 is mocked as a string, which works for both v4 and v5 of mongoose, however, v5 also has support of passing a JS Type Number. 

My company is not only taking advantage of this, but we also have some fields with _set_ and _get_ defined as functions expecting Number types, which blows up when using this library. 

So, my first thought was to fork and make changes, which I have. But returning type Number from decimal128 generator function fails v4 tests, for good reason: mongoose v4 does not support Number. 

The best solution I can come up with is some kind of "global option" object that can be called when instantiating Mocker class. Obviously this would be a breaking change for this library. 

If you are ok with that, I'll submit PR, as I would prefer to give credit where it's due. Otherwise, I'll publish another module, being sure to mention that this library and its author are the basis for the new lib. 

Please advise, and thank you for the great work!

**Comment by jsrhodes15** [comment]
I would also like to mention that I'm open to other solutions for this particular problem I'm having...

**Comment by faboulaws** [comment]
Hey
Thanks for teh feedback. I have a similar issue with ObjectId. See dock here https://github.com/faboulaws/fakingoose#generating-objectid-values

I can add an option to stringify by default and skip on demand. This can be done with the options.

**Comment by faboulaws** [comment]
See update here https://github.com/faboulaws/fakingoose/commit/f61869997f5109791d3518660a3ea32f80cf0314 .
Hope it solves your problem.

**Comment by jsrhodes15** [comment]
Ah yes I did see the option for ObjectID, and thank you for providing an update for Decimal128!

This gets me halfway there: I've been trying to figure out a way to set this "globally". So rather than having to set the property for each field in the options, we could tell the mocker class that we want all decimal128's to be Number. 

Any thoughts?

**Comment by faboulaws** [comment]
I added the option to set options globally here https://github.com/faboulaws/fakingoose#global-settings-1

**Comment by faboulaws** [comment]
@jsrhodes15 let me know how this solves your problem so I can close this issue.

**Comment by jsrhodes15** [comment]
This is EXACTLY what I was looking for! Thank you
