### ISSUE TITLE
Refactor test suite (and thank you!)

### ISSUE THREAD

**Issue by jsrhodes15** [faboulaws/fakingoose#27]
Hi @faboulaws 

Thank you for your prompt response on a previous issue. Your solution(s) were exactly what my team and I were looking for. 

While I was off trying to fix this on my own, I tried to ensure the tests still passed at all times. I have to say though, the tests are a bit clunky. I found an interesting feature of npm that might make things simpler: aliasing modules. 

I will provide a PR and you will see that all of the required versions of mongoose are installed:
```
{ ...
    "mongoose3": "npm:mongoose@^3.9.7",
    "mongoose4": "npm:mongoose@^4.13.21",
    "mongoose5": "npm:mongoose@^5.10.14",
    "mongooseLatest": "npm:mongoose@^5.10.14",
... }
```

Please let me know what you think!

**Comment by faboulaws** [comment]
Thanks for your initiative. I also updated travis.yml to reflect your changes. Thank you again. I also had the opportunity to learn something new. Did not know about the alias feature in NPM.
