### ISSUE TITLE
staticValue fails to setup if value is false

### ISSUE THREAD

**Issue by beastmike1** [faboulaws/fakingoose#30]
https://github.com/faboulaws/fakingoose/blob/422c0e382657ae43a84dbd85fe3ed31d5e56fad4/lib/mocker.js#L136

```if (staticValue && !isPlainObject(staticValue)) {```

should be replaced with

```if (typeof staticValue !== 'undefined' && !isPlainObject(staticValue)) {```

**Comment by faboulaws** [comment]
Oops. Fixing it

**Comment by faboulaws** [comment]
Fixed. Please validate, then close this issue 😃. Good catch by the way.

**Comment by beastmike1** [comment]
Now it's working properly, thanks a lot. And good job with this library, it's very useful.
