### ISSUE TITLE
Types for typescript

### ISSUE THREAD

**Issue by beastmike1** [faboulaws/fakingoose#33]
Hi, I'm currently using your package with typescript and despite It's working good i'm missing the types. I'm not very experienced on it but i did a basic ones that at least helps out with the inputs and outputs, factoryOptions still incomplet but I let them here in case it can help someone else.

```typescript
declare module 'fakingoose' {
    import {
        Model,
        Schema,
        Document,
        SchemaDefinition,
        DocumentDefinition,
    } from 'mongoose';

    class Moker<T extends Document> {
        schema: Schema;
        constructor(p: Model<Document<T>>);
        constructor(
            p: Schema<T, Model<T>, SchemaDefinition<DocumentDefinition<T>>>,
        );
        generate(staticFields: Partial<T>): T;
    }

    interface factoryOptions {
        [k: string]: any;
    }

    function factory<T extends Document>(
        p: Model<T>,
        options?: factoryOptions,
    ): Moker<T>;

    function factory<T extends Document>(
        p: Schema<T, Model<T>, SchemaDefinition<DocumentDefinition<T>>>,
        options?: factoryOptions,
    ): Moker<T>;

    export = factory;
}
```

**Comment by faboulaws** [comment]
Good Idea. I planned to rewrite the whole thing in typescript but time is a high currency. Thanks for your contribution. I'll create a `.d.ts` file soon to help with types.

**Comment by faboulaws** [comment]
I am using typescript to auto-generate declaration files. Let me know if it is satisfactory.

**Comment by beastmike1** [comment]
Yes, as far as I know if you developed the module in typescript, the d.ts files will be auto generated correctly.

**Comment by beastmike1** [comment]
In your version 
![image](https://user-images.githubusercontent.com/11091851/110111946-61e4cc80-7db1-11eb-8f94-697c4c6cb0d5.png)
![image](https://user-images.githubusercontent.com/11091851/110111998-732dd900-7db1-11eb-8a6d-c0e9f6f5fd4b.png)

In my version
![image](https://user-images.githubusercontent.com/11091851/110112075-88a30300-7db1-11eb-934c-ada923c2565f.png)
![image](https://user-images.githubusercontent.com/11091851/110112147-9f495a00-7db1-11eb-9e2b-3afe27998c0b.png)

I see that the auto-generated types are putting any everywere so it's more or less the same as before.
```typescript
export function generate(schema: any, { options, staticFields, globalOptions }: {
    options: any;
    staticFields: any;
    globalOptions: any;
}): {};
```
If I have time i will create a codesandbox with an example

**Comment by beastmike1** [comment]
Here you have a usecase
https://codesandbox.io/s/fakingoose-types-fw8ul

**Comment by faboulaws** [comment]
Great. I think I will convert the js to ts using your declaration as a basis. One challenge here is that this package support multiple version of mongoose. Not sure if the APIs across versions are the same. If u noticed mongoose is not a dependency.

**Comment by faboulaws** [comment]
I am gonna do a full rewrite in typescript.

**Comment by faboulaws** [comment]
Please upgrade to 2.0.0. The project was migrated to typescript. Still a work in progress though :-).

**Comment by beastmike1** [comment]
Factory should have the options parameter as optional. And I think that we should find way for if some one doesn't want to provide the types of the schema, because now if you don't provide the types it fails. I have updated the codesandbox to show you what i mean.

https://codesandbox.io/s/fakingoose-types-fw8ul?file=/src/index.ts

**Comment by faboulaws** [comment]
> Factory should have the options parameter as optiona
Made factory option  parameter optional. Will look into second problem
> And I think that we should find way for if some one doesn't want to provide the types of the schema, because now if you don't provide the types it fails. I have updated the codesandbox to show you what i mean.

Looking at it soon.
