### ISSUE TITLE
Array of enums fails to cast

### ISSUE THREAD

**Issue by estebanfa** [faboulaws/fakingoose#38]
Hi, i have a schema defined as 
``` javascript
{
    example: [{ type: String, enum: ['example1', 'example2'] }]
}
```
And it fails to cast it, it use random data besides using the enum but if I don't do it as Array it works.

https://github.com/faboulaws/fakingoose/blob/634a83bf34c92d444492317c7a8aab1585cae7e5/lib/generate.ts#L57

If i change that line for

``` javascript
return Array.from(Array(num)).map(() => generator(pathDef.caster, { options, globalOptions }));
```
It works, Thanks.

**Comment by faboulaws** [comment]
Fixed. Please review and close the issue. And Thanks :-).
