### ISSUE TITLE
Way to "project" some properties generation

### ISSUE THREAD

**Issue by jesusvalle** [faboulaws/fakingoose#39]
Hello!

I'm doing some tests, and I have a client document with all the properties autogenerated, except a couple that I want to control.

For example, in one of my tests, I want to check that an object in the document doesn't exist (don't generate it later my function). I have tried to overwrite it with "undefined" or an empty object, but it doesn't work, it always returns me an object with the properties that were previously autogenerated.

`await db.createClient({
                infoDeactivation: {},
}),`

Returns: { done: false, date: +089170-09-26T08:34:31.300Z, eraseDone: true }

I have also tried to skip from the factory to that object so that it does not autogenerate, but the problem is that then it does not let me set it manually in each case, returning undefined.

```
const clientFactory = factory(clientsService.clientModel, {
            infoDeactivation: { skip: true },
});
```

Perhaps it would be a good option to have some option like mongo's "project" to indicate which properties can be generated and which cannot.

**Comment by faboulaws** [comment]
Can you provide more code snippets to explain the problem? 

If my understanding is right, a solution would be to use 2 factories where the second one is configured to skip certain fields. Does that work for you?

**Comment by faboulaws** [comment]
Update your package version, then you can now override the default option per mock generated.


```javascript
const clientFactory = factory(clientsService.clientModel, {
 infoDeactivation: { skip: true },
});
```

```javascript
clientFactory.generate() // will use the default option, infoDeactivation is skipped
clientFactory.generate({},{}) // will not use the default option, infoDeactivation is not skipped
```
