### ISSUE TITLE
Unable to override defaults set by factory options

### ISSUE THREAD

**Issue by DHoefakker** [faboulaws/fakingoose#40]
Imagine the folowing:

```
const options: any = {
  'location' : { value : { internal : { type : 'Point', coordinates : [1,1] }}},
};

const exampleFactory = factory(Example, options).setGlobalObjectIdOptions({ tostring: false });

module.exports = [
  exampleFactory.generate( { _id : Types.ObjectId('60b4b91e9339c965303aaa10') } ),
  exampleFactory.generate( { _id : Types.ObjectId('60b4b91e9339c965303baa11'), 'location' : { internal : { type : 'Point', coordinates : [3,3] }}} )
];

```

In the above example i would expect that the first item would get the location set by the options. And the second one the location as set on that line.

The result however is that all items generated are getting the value set by the options.

The only way to make this work is don't use the options and set the value on each of the lines (in my case it are not 2 lines ;-))

It would be great and clean if values set by options can by override by individual lines.

**Comment by faboulaws** [comment]
Thanks for finding this bug. Issue fixed.
